#!/usr/bin/env bash
#
# A wizard - walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# --------------------------------------------------------------------------
# Wizard library - delightful, consistent UX. Identical across every wizard.
# --------------------------------------------------------------------------

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear - wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" - opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages * about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later - it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> - clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s> Stage %s/%s * %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." - a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." - a numbered-feeling action the human takes in the browser.
step() { printf '  %s*%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s! %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL - open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %sopening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser - visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser - visit it manually: $url"
}

# pause "msg" - wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" - y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY - current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" - read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" - like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE - upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %sOK wrote%s %s -> %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE - set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %sOK set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name - gh not ready; set it later"
}

# set_var NAME VALUE - set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %sOK set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name - gh not ready; set it later"
}

# finish - clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  OK Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# --------------------------------------------------------------------------
# STAGES - author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# --------------------------------------------------------------------------

TOTAL_STAGES=5
TOTAL_MINUTES=12

PROJECT_NAME="research-domain-writing"
PROJECT_VERSION=""
PYPI_TOKEN=""

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    warn "missing required command: $1"
    exit 1
  fi
}

run_cmd() {
  say "$ $*"
  "$@"
}

require_cmd git
require_cmd uv
require_cmd python3
require_cmd shellcheck
if [[ ! -f pyproject.toml || ! -d src/rdw ]]; then
  warn "run this from the research-domain-writing repo root"
  exit 1
fi
PROJECT_VERSION="$(python3 -c 'import tomllib; from pathlib import Path; print(tomllib.loads(Path("pyproject.toml").read_text(encoding="utf-8"))["project"]["version"])')"

banner "RDW PyPI publish"

stage "Release preflight" 2
say "This wizard publishes ${PROJECT_NAME} ${PROJECT_VERSION} to PyPI."
say "It assumes the release commit is already merged to main and tagged v${PROJECT_VERSION}."
CURRENT_BRANCH="$(git branch --show-current)"
CURRENT_HEAD="$(git rev-parse HEAD)"
TAG_HEAD="$(git rev-list -n 1 "v${PROJECT_VERSION}" 2>/dev/null || true)"
if [[ "$CURRENT_BRANCH" != "main" ]]; then
  warn "current branch is $CURRENT_BRANCH, not main"
  exit 1
fi
if [[ "$TAG_HEAD" != "$CURRENT_HEAD" ]]; then
  warn "v${PROJECT_VERSION} does not point at HEAD"
  say "HEAD: $CURRENT_HEAD"
  say "tag:  ${TAG_HEAD:-missing}"
  exit 1
fi
if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
  warn "tracked working tree changes are present; commit or revert them before publishing"
  git status --short
  exit 1
fi
run_cmd uv lock --check
run_cmd python3 scripts/sync-package-assets.py --check
run_cmd shellcheck scripts/*.sh
say "main and v${PROJECT_VERSION} both point at $CURRENT_HEAD."
say "Untracked files are ignored by this preflight; generated build folders are expected."
pause "Preflight looks good. Continue?"

stage "Build distributions" 2
say "Rebuild the source distribution and wheel from the current tag."
if confirm "Remove old build artifacts and rebuild with uv build?"; then
  rm -rf build dist src/research_domain_writing.egg-info
  run_cmd uv build
else
  warn "using existing dist/ artifacts"
fi
if [[ ! -f "dist/research_domain_writing-${PROJECT_VERSION}.tar.gz" ]]; then
  warn "missing dist/research_domain_writing-${PROJECT_VERSION}.tar.gz"
  exit 1
fi
if [[ ! -f "dist/research_domain_writing-${PROJECT_VERSION}-py3-none-any.whl" ]]; then
  warn "missing dist/research_domain_writing-${PROJECT_VERSION}-py3-none-any.whl"
  exit 1
fi
say "Built artifacts are present in dist/."

stage "Create or paste PyPI token" 4
say "For the first publish of a new PyPI project, create an account-scoped API token."
open_url "https://pypi.org/manage/account/token/"
step "Sign in to PyPI."
step "Create an API token. Scope: entire account, because this project may not exist yet."
step "Copy the token. It starts with pypi-."
step "Close the PyPI token tab after copying. Keep no token page open."
ask_secret PYPI_TOKEN "Paste the PyPI token:"
if [[ "$PYPI_TOKEN" != pypi-* ]]; then
  warn "PyPI tokens usually start with pypi-; check what you pasted"
  confirm "Use this value anyway?" || exit 1
fi
say "Token captured in memory only. It was not written to disk."

stage "Dry-run publish check" 2
say "Run uv publish --dry-run with the token to validate files and auth path without uploading."
if confirm "Run dry-run publish check now?"; then
  say "$ UV_PUBLISH_TOKEN=*** uv publish --dry-run"
  UV_PUBLISH_TOKEN="$PYPI_TOKEN" uv publish --dry-run
else
  warn "skipped dry-run publish check"
fi

stage "Publish to PyPI" 2
warn "This is irreversible for version ${PROJECT_VERSION}; PyPI will not let you replace the same version."
say "Files to upload:"
say "  - dist/research_domain_writing-${PROJECT_VERSION}.tar.gz"
say "  - dist/research_domain_writing-${PROJECT_VERSION}-py3-none-any.whl"
if confirm "Publish ${PROJECT_NAME} ${PROJECT_VERSION} to PyPI now?"; then
  say "$ UV_PUBLISH_TOKEN=*** uv publish"
  UV_PUBLISH_TOKEN="$PYPI_TOKEN" uv publish
  say "Open the package page and verify the release."
  open_url "https://pypi.org/project/${PROJECT_NAME}/${PROJECT_VERSION}/"
  step "Confirm the version, README, files, and install command look right."
  pause "Close the PyPI package tab when verified."
else
  warn "publish skipped"
  SKIPPED+=("PyPI upload: rerun this wizard or run UV_PUBLISH_TOKEN=... uv publish")
fi

finish
